# **Лабораторная работа №3. NumPy**

## **Задание**

In [1]:
import numpy as np
np.version.version

'2.0.2'

1. Создать массив 10x10 со случайными значениями, найти минимум и максимум (низкая)

In [2]:
z = np.random.randint(0, 100, size=(10, 10))
print(z)
print(f"Минимум: {np.min(z)}, Максимум: {np.max(z)}")

[[32 98 87 60  4 50 94 45 35 85]
 [65  9 87 17 93 50 46 66 46  3]
 [42 10 86 48 29 59 54 15 79 13]
 [ 3 67 33 77 74  8  6 88 73 26]
 [95 74 94 42 89 98 99 29 38 18]
 [72 78 62 46 54  7 84 86 27 68]
 [57  4 50 57 98 98 20 42  3 73]
 [ 4 61 82 70 65 83 15 73 65 70]
 [32  1 95 97 67 13 54 40 39 90]
 [40 48 32 78 15 76 78 65 89 81]]
Минимум: 1, Максимум: 99


2. Создать 8x8 матрицу и заполнить её единицами и нулями в шахматном порядке

In [3]:
z = np.zeros((8, 8), dtype=int)
z[1::2, ::2] = 1
z[::2, 1::2] = 1
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


3. Дан массив из 11 элементов, поменять знак у элементов, значения которых между 3 и 8

In [4]:
Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


4. Найти среднее заначение строки матрицы и вычесть его из каждого елемента строки

In [5]:
z = np.random.rand(5, 10)
row_means = np.mean(z, axis=1, keepdims=True)

result = z - row_means

print("Исходная матрица:")
print(z)
print("\nСредние значения строк:")
print(np.mean(z, axis=1))
print("\nРезультат после вычитания среднего:")
print(result)

Исходная матрица:
[[0.07916539 0.1475863  0.04622966 0.86554676 0.02655894 0.23763245
  0.73198677 0.60416863 0.14082284 0.8514299 ]
 [0.70656933 0.69233552 0.19129737 0.09835574 0.10171831 0.20939264
  0.58077687 0.63101209 0.60811256 0.90400434]
 [0.43852974 0.78701257 0.05787495 0.54366085 0.51763325 0.42599561
  0.09562535 0.77026143 0.03789097 0.16246909]
 [0.64098683 0.93933864 0.07871051 0.54356903 0.46327402 0.7585801
  0.08407916 0.09013528 0.8162879  0.0058585 ]
 [0.21878096 0.1432236  0.72182056 0.99545256 0.48418482 0.24353784
  0.07082169 0.67846829 0.61706706 0.53935754]]

Средние значения строк:
[0.37311276 0.47235748 0.38369538 0.442082   0.47127149]

Результат после вычитания среднего:
[[-0.29394738 -0.22552647 -0.32688311  0.49243399 -0.34655383 -0.13548031
   0.35887401  0.23105587 -0.23228993  0.47831714]
 [ 0.23421186  0.21997804 -0.28106011 -0.37400174 -0.37063917 -0.26296484
   0.10841939  0.15865461  0.13575508  0.43164687]
 [ 0.05483436  0.40331719 -0.32582043 

5. Поменяйте 1 и 2 строки матрицы

In [6]:
z = np.arange(25).reshape(5,5)
z[[0,1]] = z[[1,0]]
print(z)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


6. Дан массив 10x2 подеставлющий собой точки в декартовой системе координат, преобразовать в полярную

In [9]:
z = np.random.random((10,2))
X,Y = z[:,0], z[:,1]
R = np.hypot(X, Y)
T = np.arctan2(Y,X)
print(R)
print(T)

[1.21811786 0.59217046 0.61279733 0.81268113 0.86983558 0.50814684
 0.66039184 0.73084123 0.91854057 0.43515957]
[0.70030894 0.05130004 0.51780657 0.13908641 0.75726942 1.08591852
 0.73466475 0.22216111 1.036573   0.04226145]


7. Заменить максимальный элемент массива на ноль

In [26]:
z = np.random.random(10)
z[z.argmax()] = 0
print(z)

[0.05379094 0.26684719 0.1347728  0.         0.47313722 0.06882372
 0.26028944 0.81939531 0.70571279 0.04026875]


8. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве. Добавление производиться только 1 раз

In [28]:
z = np.ones(10)
i = np.random.randint(0,len(z),20)
print(f"Исходный массив: {z}")
print(f"Индексы для добавления: {i}")
np.add.at(z, i, 1)
print(f"После добавления 1: {z}")

Исходный массив: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Индексы для добавления: [9 9 6 0 9 0 1 1 9 3 2 8 2 2 1 8 1 7 2 5]
После добавления 1: [3. 5. 5. 2. 1. 2. 2. 2. 3. 5.]


9. Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [57]:
z = np.array([1,2,3,4,5])
result = np.zeros(len(z) + (len(z) - 1) * 3)
result[::4] = z
print(f"Исходный вектор: {z}")
print(f"Результат с тремя нулями: {result}")
print()

Исходный вектор: [1 2 3 4 5]
Результат с тремя нулями: [1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]



10. Найти ближайшее к заданному значению число в заданном массиве

In [72]:
z = np.arange(100)
v = np.random.uniform(0,100)
nearest_index = np.argmin(np.abs(z - v))
nearest_value = z[nearest_index]
print(f"Искомое значение: {v:.1f}")
print(f"Ближайшее значение: {nearest_value}")
print(f"Индекс ближайшего значения: {nearest_index}")

Искомое значение: 34.6
Ближайшее значение: 35
Индекс ближайшего значения: 35
